# default config is always loaded, env config (eg testnet) is loaded using the argument passed into the loadAsync function
default:
  api_url: "http://localhost:3000"
testnet:
  pk: yourpkhere
  mnemonic: ""
  fallBackAddress: "0xb13CD07B22BC5A69F8500a1Cb3A1b65618d50B22"
mainnet:
  pk:
  mnemonic: ""
  fallBackAddress:
